### ISSUE TITLE
Optional address is required in bloxone_dns_delegation for external secondaries

### ISSUE THREAD

**Issue by nautikos** [infobloxopen/terraform-provider-bloxone#146]
When defining a zone delegation with an external DNS authoritative server the terraform outputs:
``` terraform
bloxone_dns_delegation.del_example_ch: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to bloxone_dns_delegation.del_example_ch, provider "provider[\"registry.terraform.io/infobloxopen/bloxone\"]" produced an unexpected new value:
│ .delegation_servers[0].address: was null, but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Here's the config we're using:
``` terraform
resource "bloxone_dns_delegation" "del_example_ch" {
  fqdn = "del.example.ch."
  delegation_servers = [
    {
    fqdn = "ns1.test.com."
    }
  ]

  view    = bloxone_dns_views.osag_internal.id
}
```

According to your [documentation](https://registry.terraform.io/providers/infobloxopen/bloxone/latest/docs/resources/dns_delegation#nested-schema-for-delegation_servers), the `address` field is only required when fqdn of a delegation server falls under delegation fqdn. However, it seems the backend requires the `address` field regardless. Adding the delegation through GUI (CSP Portal) doesn't work either as it says "IP ADDRESS This is a required field"

**Comment by mathewab** [comment]
Hi, 

Thank you for reporting the issue. As mentioned in the API, the `address` is optional when the delegation server's fqdn falls under the delegation fqdn. I will report an issue internally to see why it shows up as an error in the UI. 

The non-empty plan that you get is because, the API in such scenario sends back an empty string `""` which it thinks is different from `null`. This should be fixed in https://github.com/infobloxopen/terraform-provider-bloxone/pull/148 

Thanks.
